kind: pipeline
type: docker
name: build

steps:
  - name: install
    image: node:20
    commands:
      - npm install
      - npm ci

  - name: hello
    image: node:20
    commands:
      # bug with ReferenceError: structuredClone is not defined
      # Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
      - npm i
      - echo "Hello World! Building Vue.js project...!"
      - npm run build

trigger:
  branch:
    - main
    - master
  event:
    - push
    - pull_request
    - custom
    - promote
    - rollback

---
kind: pipeline
type: docker
name: build-and-deploy

steps:
  - name: install
    image: node:20
    commands:
      - npm install
      - npm ci

  - name: hello
    image: node:20
    commands:
      # bug with ReferenceError: structuredClone is not defined
      # Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
      - npm i
      - echo "Hello World! Building Vue.js project...!"
      - npm run build

  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: tajulasri443/saas-landing-page
      tags:
        - latest
      dockerfile: Dockerfile

trigger:
  event:
    - promote
  target:
    - production
    - development
    - rc-release
