kind: pipeline
type: docker
name: build

steps:
  - name: install
    image: node:16
    commands:
      - npm install
      - npm ci

  - name: hello
    image: node:16
    commands:
      - echo "Hello World! Building Vue.js project...!"
      - npm run build

trigger:
  branch:
    - main
    - master
  event:
    - push
    - pull_request
    - custom
    - promote
    - rollback
